import {  Work_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";

const work_sans = Work_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "News Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={work_sans.className}>
        <NavBar/>
        {children}
        </body>
    </html>
  );
}
